export const data = [
    { id: "1", quote: "Talent is nothing more than a pursued interest." },
    { id: "2", quote: "The world isn’t fair. It's your job to make it so." },
    { id: "3", quote: "Equality is a fantasy." },
    { id: "4", quote: "A person's true nature is revealed in times of adversity." },
    { id: "5", quote: "Trust is an illusion; people only act in their own self-interest." },
    { id: "6", quote: "Emotions cloud judgment; stay rational to stay ahead." },
    { id: "7", quote: "Manipulation is simply understanding others better than they understand themselves." },
    { id: "8", quote: "The strong win; the weak lose. That’s the only rule." },
    { id: "9", quote: "Effort is admirable, but results are what matter." },
    { id: "10", quote: "Loyalty can be manufactured; it's rarely genuine." },
    { id: "11", quote: "Never reveal your true self to anyone." },
    { id: "12", quote: "Humans are driven by fear and desire." },
    { id: "13", quote: "I don’t care about winning or losing; I care about control." },
    { id: "14", quote: "Sometimes, silence is the loudest response." },
    { id: "15", quote: "People often fear what they cannot understand." },
    { id: "16", quote: "To achieve your goals, you must be willing to discard your morals." },
    { id: "17", quote: "Victory is just a series of well-executed steps." },
    { id: "18", quote: "It’s easier to act than to explain." },
    { id: "19", quote: "People see what they want to see." },
    { id: "20", quote: "Sometimes, the best strategy is to do nothing at all." },
    { id: "21", quote: "The smartest people know when to feign ignorance." },
    { id: "22", quote: "The line between ally and enemy is thinner than you think." },
    { id: "23", quote: "All relationships are transactions at their core." },
    { id: "24", quote: "The best lies are rooted in truth." },
    { id: "25", quote: "Most people are predictable; that’s their greatest weakness." },
    { id: "26", quote: "Strength is knowing when to act and when to wait." },
    { id: "27", quote: "The only constant is change; adapt or fall behind." },
    { id: "28", quote: "Always keep your options open." },
    { id: "29", quote: "The greatest threat is the one you never see coming." },
    { id: "30", quote: "What you see on the surface is rarely the truth." },
    { id: "31", quote: "In the end, everyone fights for their own benefit." },
    { id: "32", quote: "Freedom comes from understanding the rules and bending them." },
    { id: "33", quote: "Fear is a more powerful motivator than love." },
    { id: "34", quote: "Plans fail because people overestimate their abilities." },
    { id: "35", quote: "It’s not about being the best; it’s about being indispensable." },
    { id: "36", quote: "Even the smallest actions can have the greatest consequences." },
    { id: "37", quote: "People want to believe in something, even if it’s a lie." },
    { id: "38", quote: "Truth and deception are tools; use them wisely." },
    { id: "39", quote: "Sacrifice is inevitable; the key is deciding what to sacrifice." },
    { id: "40", quote: "Knowledge is power, but it’s useless without action." },
    { id: "41", quote: "Weakness invites exploitation." },
    { id: "42", quote: "Control the narrative, and you control the outcome." },
    { id: "43", quote: "Perception shapes reality more than truth does." },
    { id: "44", quote: "In a game of chess, the pawns are as important as the king." },
    { id: "45", quote: "Never let anyone know your next move." },
    { id: "46", quote: "Every situation has a loophole; you just need to find it." },
    { id: "47", quote: "Adaptability is the essence of survival." },
    { id: "48", quote: "Emotion is a liability; logic is your greatest weapon." },
    { id: "49", quote: "A victory without struggle is hollow." },
    { id: "50", quote: "The art of winning is in not appearing to fight at all." },
    { id: "51", quote: "People always act in their own interest, even if they deny it." },
    { id: "52", quote: "The easiest way to control someone is to give them what they want." },
    { id: "53", quote: "Strength without strategy is nothing more than brute force." },
    { id: "54", quote: "Appearances can be more important than reality." },
    { id: "55", quote: "Sometimes, the best way to win is to let others think they have." },
    { id: "56", quote: "You can’t force someone to change; they must want it themselves." },
    { id: "57", quote: "The line between genius and insanity is results." },
    { id: "58", quote: "Actions speak louder than words, but intentions matter more." },
    { id: "59", quote: "A calculated risk is better than blind caution." },
    { id: "60", quote: "Fear is the most effective tool to control others." },
    { id: "61", quote: "Observation is the key to understanding people." },
    { id: "62", quote: "The ability to adapt is more important than the ability to lead." },
    { id: "63", quote: "The true test of character is what you do when no one is watching." },
    { id: "64", quote: "Most people prefer a comforting lie over an uncomfortable truth." },
    { id: "65", quote: "True strength comes from knowing your own weaknesses." },
    { id: "66", quote: "It's not about being better; it’s about being smarter." },
    { id: "67", quote: "Never underestimate the power of a desperate person." },
    { id: "68", quote: "Chaos can be a ladder if you know how to climb it." },
    { id: "69", quote: "Your greatest enemy is often yourself." },
    { id: "70", quote: "Reputation is everything; protect it at all costs." },
    { id: "71", quote: "Even a cornered animal can be dangerous." },
    { id: "72", quote: "Loyalty is a currency, and like any currency, it can be spent." },
    { id: "73", quote: "It’s not enough to win; you have to make others believe you deserve it." },
    { id: "74", quote: "To understand someone, you must first understand their fears." },
    { id: "75", quote: "Trust can be broken with a single lie." },
    { id: "76", quote: "Your words mean nothing without the power to back them up." },
    { id: "77", quote: "Conflict reveals the true nature of people." },
    { id: "78", quote: "Winning isn’t about skill; it’s about preparation." },
    { id: "79", quote: "The most valuable thing you can own is someone else’s trust." },
    { id: "80", quote: "The key to victory is to anticipate your opponent’s moves." },
    { id: "81", quote: "Never confuse kindness with weakness." },
    { id: "82", quote: "Patience is a weapon, and time is your ally." },
    { id: "83", quote: "Leverage is the ability to make others do what you want." },
    { id: "84", quote: "Sacrifices must be made to achieve great things." },
    { id: "85", quote: "True power is the ability to control yourself." },
    { id: "86", quote: "Knowledge is only useful if you know how to use it." },
    { id: "87", quote: "Most people are prisoners of their own desires." },
    { id: "88", quote: "A single mistake can undo years of work." },
    { id: "89", quote: "In life, there are no guarantees—only opportunities." },
    { id: "90", quote: "Sometimes, the best way to win is not to play at all." }
];
